export const FETCH_STUDENTS_SUMMERY = "FETCH_STUDENTS_SUMMERY";

export const FETCH_BOOKS_SUMMERY = "FETCH_BOOKS_SUMMERY";

export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const FETCH_SINGLE_STUDENT = "FETCH_SINGLE_STUDENT";
export const UPLOAD_STUDENT_IMAGE = "UPLOAD_STUDENT_IMAGE";

export const FETCH_INACTIVE_STUDENTS = "FETCH_INACTIVE_STUDENTS";

export const FETCH_ALL_DEPARTMENTS = "FETCH_ALL_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";

export const FETCH_ALL_BATCHES = "FETCH_ALL_BATCHES";
export const ADD_BATCH = "ADD_BATCH";
export const FETCH_BATCH = "FETCH_BATCH";

export const FETCH_BOOKS_AVAILABLE = "FETCH_BOOKS_AVAILABLE";
export const ADD_BOOK = "ADD_BOOK";
export const FETCH_BOOK = "FETCH_BOOK";
export const FETCH_ALL_BOOKS_ONLY_NAMES = "FETCH_ALL_BOOKS_ONLY_NAMES";

export const FETCH_BOOKS_BORROWED = "FETCH_BOOKS_BORROWED";
export const ADD_BORROWER = "ADD_BORROWER";
export const FETCH_SINGLE_BORROWER = "FETCH_SINGLE_BORROWER";
export const DELETE_BORROWER = "DELETE_BORROWER";
