export const FETCH_STUDENTS_SUMMERY = "FETCH_STUDENTS_SUMMERY";

export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const FETCH_SINGLE_STUDENT = "FETCH_SINGLE_STUDENT";
export const UPLOAD_STUDENT_IMAGE = "UPLOAD_STUDENT_IMAGE";

export const FETCH_INACTIVE_STUDENTS = "FETCH_INACTIVE_STUDENTS";

export const FETCH_ALL_DEPARTMENTS = "FETCH_ALL_DEPARTMENTS";

export const FETCH_BOOKS_AVAILABLE = "FETCH_BOOKS_AVAILABLE";

export const FETCH_BOOKS_BORROWED = "FETCH_BOOKS_BORROWED";
